name: CMS_ACCOUNT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cms_account_production:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Pull
      run: git pull origin master
      working-directory: /var/www/account_cms
    - name: Build Node
      run: npm run build
      working-directory: /var/www/account_cms/resources/coreui
    - name: Complete
      run: npm run dev
      working-directory: /var/www/account_cms
